"""empty message

Revision ID: 0dfedfb90183
Revises: 
Create Date: 2021-04-22 12:05:23.649179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfedfb90183'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Properties',
    sa.Column('property_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Property_Title', sa.String(length=80), nullable=True),
    sa.Column('Description', sa.String(length=80), nullable=True),
    sa.Column('num_rooms', sa.String(length=80), nullable=True),
    sa.Column('num_bathrooms', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('property_type', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('photo', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('property_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Properties')
    # ### end Alembic commands ###
